In [1]:
import numpy as  np

In [4]:
# Tensor con ndim (rango o número de ejes) 0 --> escalar
x = np.array(12)
x.ndim

0

In [18]:
# Tensor con ndim (rango o número de ejes) 1 --> vector
x = np.array([12, 5, 17 -8])
x.ndim

1

In [19]:
x.shape

(3,)

In [16]:
# Tensor con ndim (rango o número de ejes) 2 --> matriz
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2],
              [-2, 4, 7, 3, -9]])
x.ndim

2

In [7]:
x.shape

(4, 5)

In [9]:
x[1]

array([ 6, 79,  3, 35,  1])

In [10]:
x[:,0]

array([ 5,  6,  7, -2])

In [15]:
# Tensor con ndim (rango o número de ejes) 3
x = np.array([[[5, 78, 2, 34, 0], [6, 79, 3, 35, 1], [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0], [6, 79, 3, 35, 1],[7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0], [6, 79, 3, 35, 1], [7, 80, 4, 36, 2]]])

In [13]:
x.ndim

3

In [14]:
x.shape

(3, 3, 5)

In [20]:
x= np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\Miguel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\miguel\appdata\local\programs\python\python310\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

==========

In [ ]:
x= np.random

In [21]:
x= np.random??

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\Miguel\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\miguel\appdata\local\programs\python\python310\lib\site-packages\numpy\random\__init__.py
Source:     
"""
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

======

In [ ]:
x= np.random

In [22]:
x= np.random.randint??

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

In [ ]:
x= np.random.randint

In [23]:
x1 = np.random.randint(0, 100, size=(5, 7))

In [24]:
x1

array([[37, 44, 80, 88, 91, 21, 18],
       [63, 89, 70, 36, 84, 99, 75],
       [19, 91, 50, 73,  3, 12, 61],
       [18, 81, 39, 89, 80, 53, 10],
       [82, 47, 87, 27, 48, 73, 92]])

In [26]:
x2= np.random.randint(0, 10, size=(5, 7))

In [27]:
x2

array([[0, 7, 6, 2, 5, 3, 7],
       [4, 6, 7, 2, 9, 3, 7],
       [8, 3, 2, 9, 3, 3, 8],
       [3, 3, 8, 5, 3, 4, 1],
       [6, 8, 9, 0, 2, 6, 5]])

In [28]:
x= x1 + x2

In [29]:
x

array([[ 37,  51,  86,  90,  96,  24,  25],
       [ 67,  95,  77,  38,  93, 102,  82],
       [ 27,  94,  52,  82,   6,  15,  69],
       [ 21,  84,  47,  94,  83,  57,  11],
       [ 88,  55,  96,  27,  50,  79,  97]])

In [32]:
x3 = np.empty(x1.shape)
for row in range(x1.shape[0]):
    for col in range(x1.shape[1]):
        x3[row, col] = x1[row, col] + x2[row, col]

In [33]:
x3

array([[ 37.,  51.,  86.,  90.,  96.,  24.,  25.],
       [ 67.,  95.,  77.,  38.,  93., 102.,  82.],
       [ 27.,  94.,  52.,  82.,   6.,  15.,  69.],
       [ 21.,  84.,  47.,  94.,  83.,  57.,  11.],
       [ 88.,  55.,  96.,  27.,  50.,  79.,  97.]])

In [34]:
x3 - x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [36]:
import time
x = np.random.random((20, 100))
y = np.random.random((20, 100))
t0 = time.time()
for _ in range(1000):
    z = x + y
    z = np.maximum(z, 0.)
print("Took: {0:.2f} s".format(time.time() - t0))

Took: 0.01 s


In [38]:
x.shape

(20, 100)

In [39]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [40]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [41]:
t0 = time.time()
for _ in range(1000):
    z = naive_add(x, y)
    z = naive_relu(z)
print("Took: {0:.2f} s".format(time.time() - t0))

Took: 2.32 s


# Broadcasting

In [52]:
X = np.random.random((32, 10))
y = np.random.random((10,))

Si quisiéramos operar (por ejemplo sumando) los dos arrays... se haría  
automáticamente un broadcast del pequeño (el segundo) para convertirlo  
a la misma forma que el grande, y después hacer la operación elemento a elemento  
Veamos el broadcasting manual de y... (no hace falta pq numpy lo hace solo, sólo  
lo hacemos para ver cómo se hace

In [53]:
y.shape

(10,)

In [57]:
y = np.expand_dims(y, axis=0)  # le añadimos un eje X, ahora ya sería una matriz
y.shape

(1, 10)

In [58]:
Y = np.concatenate([y] * 32, axis=0)

In [59]:
Y
Y.shape

(32, 10)

In [60]:
# Ahora ya podríamos operar...

In [61]:
# Por supuesto, esto no lo haremos nunca, lo hace automático numpy

In [63]:
# Producto de tensores (producto interno, dot product, como el escalar si fueran vectores)
# Es el producto normal de matrices...

In [66]:
x = np.random.random(32)
y = np.random.random(32)
x.shape

(32,)

In [67]:
np.dot(x,y)  # aquí sería un producto escalar de vectores, simplemente

7.202931512084453

In [71]:
A = np.random.random((8, 14))
B = np.random.random((14, 5))
C = np.dot(A, B)  # esto es el producto de matrices... (es como el pro. escalar... cada fila por cada una de las columnas)
C.shape  # A es mxn y b debe ser n x p.... el resultado es m x p

(8, 5)

In [72]:
# Tensor reshaping

In [73]:
A = np.random.randint(0, 101, (5, 6, 4))

In [74]:
A

array([[[ 15,  39,  81,  71],
        [ 48,  85,  99,  92],
        [ 40,  93,  38,   9],
        [ 40,  37,  39,  95],
        [ 93,  67,   3,  66],
        [ 19,  29,  53,  82]],

       [[ 11,  13,  23,  56],
        [ 25,  80,  72,  96],
        [ 62,  96,  74,  82],
        [ 42,   0,  76,  30],
        [ 67,   8,   1,  61],
        [ 69,  18,  32,  77]],

       [[  4,   7,  19,   0],
        [ 73,  12, 100,  90],
        [  2,  90,  70,  41],
        [ 61,  25,  97,  50],
        [ 58,  58,  39,  94],
        [ 38,  27,  22,  52]],

       [[ 98,  62,   3,  46],
        [ 27,  68,  86,  10],
        [ 68,  47,  35,  21],
        [ 69,  22,  39, 100],
        [ 67,  82,   5,   8],
        [ 27,   8,   4,  77]],

       [[ 80,  45,  95,  55],
        [ 19,  56,  19,   4],
        [ 27,  64,  26,  29],
        [ 73,  76,  26,  68],
        [ 57,  51,  33,  34],
        [ 25,  75,  73,  41]]])

In [75]:
A = A.reshape((5, 24))

In [76]:
A

array([[ 15,  39,  81,  71,  48,  85,  99,  92,  40,  93,  38,   9,  40,
         37,  39,  95,  93,  67,   3,  66,  19,  29,  53,  82],
       [ 11,  13,  23,  56,  25,  80,  72,  96,  62,  96,  74,  82,  42,
          0,  76,  30,  67,   8,   1,  61,  69,  18,  32,  77],
       [  4,   7,  19,   0,  73,  12, 100,  90,   2,  90,  70,  41,  61,
         25,  97,  50,  58,  58,  39,  94,  38,  27,  22,  52],
       [ 98,  62,   3,  46,  27,  68,  86,  10,  68,  47,  35,  21,  69,
         22,  39, 100,  67,  82,   5,   8,  27,   8,   4,  77],
       [ 80,  45,  95,  55,  19,  56,  19,   4,  27,  64,  26,  29,  73,
         76,  26,  68,  57,  51,  33,  34,  25,  75,  73,  41]])

In [77]:
# Una forma sencilla de reshape el simpelemtne la transpuesta
A = np.transpose(A)   # o A = A.T o A = A.tranpose

In [78]:
A

array([[ 15,  11,   4,  98,  80],
       [ 39,  13,   7,  62,  45],
       [ 81,  23,  19,   3,  95],
       [ 71,  56,   0,  46,  55],
       [ 48,  25,  73,  27,  19],
       [ 85,  80,  12,  68,  56],
       [ 99,  72, 100,  86,  19],
       [ 92,  96,  90,  10,   4],
       [ 40,  62,   2,  68,  27],
       [ 93,  96,  90,  47,  64],
       [ 38,  74,  70,  35,  26],
       [  9,  82,  41,  21,  29],
       [ 40,  42,  61,  69,  73],
       [ 37,   0,  25,  22,  76],
       [ 39,  76,  97,  39,  26],
       [ 95,  30,  50, 100,  68],
       [ 93,  67,  58,  67,  57],
       [ 67,   8,  58,  82,  51],
       [  3,   1,  39,   5,  33],
       [ 66,  61,  94,   8,  34],
       [ 19,  69,  38,  27,  25],
       [ 29,  18,  27,   8,  75],
       [ 53,  32,  22,   4,  73],
       [ 82,  77,  52,  77,  41]])

In [80]:
# Transformación lineal (como giro o escala): y = Matriz dot x
# Trnasformación afín : y = Matriz dot x + b
# Una dense layer sin función de activación es una layer afín

In [81]:
# Es fácil ver que la composición de transformaciones afines es simplemente una transf. afín
# O sea, podemos resumir muchas tras. afines, una acoplada tras otra, utilizando sólo una trans. afín
# es por ello que si tenemos una red neuronal compuesta de muchas dense layer simplemente afines...
# podemos conseguir lo mismo sólo con una layer...
# Es por ello por lo que se utilizan en las layer las funciones de activación, como ReLU, etc

Thanks to activation functions, a chain of Dense layers can be made  
to implement very complex, non-linear geometric transformations, resulting  
in very rich hypothesis spaces for your deep neural networks. 