# Numerical Python (libro)

In [1]:
import numpy as np

In [2]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.ones((2, 4), dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [7]:
unos = np.ones(15)

In [8]:
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
dos = 2 * unos
dos

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [13]:
    tres = (3 * unos).reshape((5, 3))
    tres

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [15]:
np.full(10, 5.4)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [18]:
np.full((2, 5), 5.4)

array([[5.4, 5.4, 5.4, 5.4, 5.4],
       [5.4, 5.4, 5.4, 5.4, 5.4]])

In [19]:
x1 = np.empty(5)

In [20]:
x1  # No tiene valores inicialmente!!

array([2.12199579e-314, 8.86994241e-312, 5.41495948e-321, 1.06099793e-313,
       2.29178816e-312])

In [22]:
x1.fill(3.0)
x1

array([3., 3., 3., 3., 3.])

# Arrays Filled with Incremental Sequences

In [23]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
np.arange(0.0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [25]:
np.linspace(0, 10, 15)   # Genera 15 valores del 0 al 10 igualmente espaciados

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

# Arrays Filled with Logarithmic Sequences

In [26]:
# Generate an array with logarithmically distributed values between 1 and 100
np.logspace(0, 2, 5) # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [27]:
# Por defecto utiliza base 10, pero se pueden utilizar otras bases

In [28]:
np.logspace?

Signature:
np.logspace(
    start,
    stop,
    num=50,
    endpoint=True,
    base=10.0,
    dtype=None,
    axis=0,
)
Docstring:
Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at ``base ** start``
(`base` to the power of `start`) and ends with ``base ** stop``
(see `endpoint` below).

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    ``base ** start`` is the starting value of the sequence.
stop : array_like
    ``base ** stop`` is the final value of the sequence, unless `endpoint`
    is False.  In that case, ``num + 1`` values are spaced over the
    interval in log-space, of which all but the last (a sequence of
    length `num`) are returned.
num : integer, optional
    Number of samples to generate.  Default is 50.
endpoint : boolean, optional
    If true, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
base : array_like, optional
    The

# Meshgrid Arrays
Multidimensional coordinate grids can be generated using the function np.meshgrid.  
Given two one-dimensional coordinate arrays, we can generate two-dimensional coordinate arrays using the np.meshgrid function.

In [29]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)

In [37]:
X
# si imaginamos el grid, que va a tener 9 puntos, nos da los valores x de cada uno de los puntos

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [39]:
Y
# si imaginamos el grid, nos da los valores y de cada uno de los puntos

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [32]:
grid = np.meshgrid(x, y)

In [33]:
grid

[array([[-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]]),
 array([[-2, -2, -2],
        [ 0,  0,  0],
        [ 2,  2,  2]])]

A common use-case of the two-dimensional coordinate arrays, like X and Y in this example, is to evaluate functions over two variables x and y.  
For example, to evaluate the expression (x+y)2

In [35]:
Z = (X + Y) ** 2
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [42]:
A = np.array([[2, 5, 4], [3, 2, 4], [5, 2, 7], [2, -2, 4]])
A

array([[ 2,  5,  4],
       [ 3,  2,  4],
       [ 5,  2,  7],
       [ 2, -2,  4]])

In [44]:
np.ones_like(A)  # nos crea un array con la misma estructura que A, pero lleno de unos

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
np.zeros_like(A)  # lo mismo, pero lleno de ceros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [47]:
# creando matriz identidad
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
# podemos hacer lo mismo exactamente con eye, que además permite un k de desplazamiento
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [49]:
np.eye(3, k= -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [51]:
# matrices diagonales
np.diag((1, 2, -4))

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0,  0, -4]])

In [53]:
np.diag(np.arange(0, 20, 5))  # como parámetro le podemos meter cualquier secuencia

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [55]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [58]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

In [59]:
# vamos a crear un array multidimensional desde una función
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)

In [60]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [61]:
A[:, 1] # the second column

array([ 1, 11, 21, 31, 41, 51])

In [63]:
A[:3, :2] # upper half diagonal block matrix
# O sea, primero indicamos las filas, 0:3, o sea, desde el principio hasta la 3 (sin coger)
# Lo mismo para la columna, 0:2

array([[ 0,  1],
       [10, 11],
       [20, 21]])

In [64]:
A[::2, ::2] # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [66]:
A[1:4, ::2] # las filas de la 1 hasta la 3 incluidos, las columnas saltando de 2 en dos

array([[10, 12, 14],
       [20, 22, 24],
       [30, 32, 34]])

# Views...
Son distintas formas de ver un mismo array
El array no cambia en memoria, lo que cambia es nuestro punto de vista

In [68]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [69]:
# Realmente el array b no es nada nuevo, tan solo una vista de A, q se restringe
# al rango al que estamos mirando, no se crea ningún nuevo objeto

In [70]:
B[:, :] = 0

In [71]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [75]:
# Si de verdad quisiéramos crear un nuevo objeto, habría que usar .copy()
C = B[1:3, 1:3].copy()

In [76]:
C[:, :] = 1

In [77]:
C

array([[1, 1],
       [1, 1]])

In [78]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [79]:
# También los views sirve para las traspuestas por ejemplo
# sería el mismo objeto, pero cambiamos el orden de movernos...
# para el reshape...

### Fancy Indexing and Boolean-Valued Indexing