# Numerical Python (libro)

In [1]:
import numpy as np

In [3]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.ones((2, 4), dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [7]:
unos = np.ones(15)

In [8]:
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
dos = 2 * unos
dos

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [10]:
    tres = (3 * unos).reshape((5, 3))
    tres

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [11]:
np.full(10, 5.4)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [12]:
np.full((2, 5), 5.4)

array([[5.4, 5.4, 5.4, 5.4, 5.4],
       [5.4, 5.4, 5.4, 5.4, 5.4]])

In [13]:
x1 = np.empty(5)

In [14]:
x1  # No tiene valores inicialmente!!

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.02360527e-306,
       2.29178816e-312])

In [15]:
x1.fill(3.0)
x1

array([3., 3., 3., 3., 3.])

# Arrays Filled with Incremental Sequences

In [16]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
np.arange(0.0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [18]:
np.linspace(0, 10, 15)   # Genera 15 valores del 0 al 10 igualmente espaciados

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

# Arrays Filled with Logarithmic Sequences

In [19]:
# Generate an array with logarithmically distributed values between 1 and 100
np.logspace(0, 2, 5) # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [20]:
# Por defecto utiliza base 10, pero se pueden utilizar otras bases

In [21]:
np.logspace?

Signature:
np.logspace(
    start,
    stop,
    num=50,
    endpoint=True,
    base=10.0,
    dtype=None,
    axis=0,
)
Docstring:
Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at ``base ** start``
(`base` to the power of `start`) and ends with ``base ** stop``
(see `endpoint` below).

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    ``base ** start`` is the starting value of the sequence.
stop : array_like
    ``base ** stop`` is the final value of the sequence, unless `endpoint`
    is False.  In that case, ``num + 1`` values are spaced over the
    interval in log-space, of which all but the last (a sequence of
    length `num`) are returned.
num : integer, optional
    Number of samples to generate.  Default is 50.
endpoint : boolean, optional
    If true, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
base : array_like, optional
    The

# Meshgrid Arrays
Multidimensional coordinate grids can be generated using the function np.meshgrid.  
Given two one-dimensional coordinate arrays, we can generate two-dimensional coordinate arrays using the np.meshgrid function.

In [22]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)

In [23]:
X
# si imaginamos el grid, que va a tener 9 puntos, nos da los valores x de cada uno de los puntos

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [24]:
Y
# si imaginamos el grid, nos da los valores y de cada uno de los puntos

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [25]:
grid = np.meshgrid(x, y)

In [26]:
grid

[array([[-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]]),
 array([[-2, -2, -2],
        [ 0,  0,  0],
        [ 2,  2,  2]])]

A common use-case of the two-dimensional coordinate arrays, like X and Y in this example, is to evaluate functions over two variables x and y.  
For example, to evaluate the expression (x+y)2

In [27]:
Z = (X + Y) ** 2
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [28]:
A = np.array([[2, 5, 4], [3, 2, 4], [5, 2, 7], [2, -2, 4]])
A

array([[ 2,  5,  4],
       [ 3,  2,  4],
       [ 5,  2,  7],
       [ 2, -2,  4]])

In [29]:
np.ones_like(A)  # nos crea un array con la misma estructura que A, pero lleno de unos

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
np.zeros_like(A)  # lo mismo, pero lleno de ceros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
# creando matriz identidad
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
# podemos hacer lo mismo exactamente con eye, que además permite un k de desplazamiento
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [33]:
np.eye(3, k= -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [34]:
# matrices diagonales
np.diag((1, 2, -4))

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0,  0, -4]])

In [35]:
np.diag(np.arange(0, 20, 5))  # como parámetro le podemos meter cualquier secuencia

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [36]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [39]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

In [40]:
# vamos a crear un array multidimensional desde una función
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)

In [41]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [42]:
A[:, 1] # the second column

array([ 1, 11, 21, 31, 41, 51])

In [43]:
A[:3, :2] # upper half diagonal block matrix
# O sea, primero indicamos las filas, 0:3, o sea, desde el principio hasta la 3 (sin coger)
# Lo mismo para la columna, 0:2

array([[ 0,  1],
       [10, 11],
       [20, 21]])

In [44]:
A[::2, ::2] # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [45]:
A[1:4, ::2] # las filas de la 1 hasta la 3 incluidos, las columnas saltando de 2 en dos

array([[10, 12, 14],
       [20, 22, 24],
       [30, 32, 34]])

# Views...
Son distintas formas de ver un mismo array
El array no cambia en memoria, lo que cambia es nuestro punto de vista

In [46]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [47]:
# Realmente el array b no es nada nuevo, tan solo una vista de A, q se restringe
# al rango al que estamos mirando, no se crea ningún nuevo objeto

In [48]:
B[:, :] = 0

In [49]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [50]:
# Si de verdad quisiéramos crear un nuevo objeto, habría que usar .copy()
C = B[1:3, 1:3].copy()

In [51]:
C[:, :] = 1

In [52]:
C

array([[1, 1],
       [1, 1]])

In [53]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
# También los views sirve para las traspuestas por ejemplo
# sería el mismo objeto, pero cambiamos el orden de movernos...
# para el reshape...

### Fancy Indexing and Boolean-Valued Indexing

Fancy indexing  
Consiste en usar un array para indexar a otro array!!

In [57]:
A = np.linspace(0, 1, 11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [59]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [60]:
# Podemos conseguir lo mismo con fancy indexing...
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [61]:
# Boolean-value indexing...
# Consiste en pasar elementos tipo bool (True o False) y según sean pues indicará 
# que cogemos el valor o no...

In [62]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [64]:
b = A > 0.5
b

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [66]:
A[b]  # esto hace que sólo seleccionemos de A los índices que son True
# Es lo mismo que poner A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [68]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
indices = [2, 4, 6]
A[indices]

array([2, 4, 6])

Observar que los arrays conseguidos con fancy o value indexing...    
a diferencia de los conseguidos con slices, son independientes, son copias..   
o por tanto su modificación no afecta al original

In [74]:
B = A[indices]  # es una copia, no un view...
B

array([2, 4, 6])

In [75]:
B[:] = 0
B

array([0, 0, 0])

In [77]:
A   # aquí comprobamos que A no ha cambiado... esto es pq B no es un view, sino un nuevo array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
A[A<5] = 3

In [80]:
A

array([3, 3, 3, 3, 3, 5, 6, 7, 8, 9])

# Reshaping and Resizing
Reshaping an array does not require modifying the underlying array data;   
it only changes in how the data is interpreted, by redefining the array’s strides attribute  
O sea, esto no creo objetos, sino views de esos objetos
Si necesitamos una copia, hace falta utilizar el método .copy()

In [83]:
# Podemos hacerlo de dos formas:
# con la función np.reshape 
data = np.array([[1, 2], [3, 4]])
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [86]:
# y con el método .reshape
data.reshape(4)

array([1, 2, 3, 4])

In [88]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
# Crear un objeto unidimensional.... de dos formas:
# con np.ravel o con el método .ravel, lo que se crea es un view
A = np.arange(25).reshape(5, 5)
view_unidimensional = A.ravel()
view_unidimensional
# Lo mismo sería view_unidimensional = np.ravel(A)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [95]:
# Si necesitamos una copia sería con el método o la función flatten
copia_unidimensional = A.flatten()
copia_unidimensional

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [100]:
# aÑADIR dimensiones tb se puede hacer!! utilizando newaxis
data = np.arange(0, 5)
column = data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [101]:
# También podíamos haberlo hecho por filas... 
row = data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])

In [102]:
# Podemos hacer esto con la función np.expand_dims...
# data[:, np.newaxis] is equivalent to np.expand_dims(data, axis=1)
# data[np.newaxis, :] is equivalent to np.expand_dims(data, axis=0)

In [103]:
# Podemos ampliar un array utilizando np.hstack, np.vstack, np.concatenate
# hstack añade horizontalmente / vstack añade verticalmente, concatenate...
data = np.arange(5)
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [ ]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

# Expresiones vectoriales

In [108]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [109]:
x + y

array([[ 6,  8],
       [10, 12]])

In [110]:
x * y

array([[ 5, 12],
       [21, 32]])

In [111]:
x * 2

array([[2, 4],
       [6, 8]])

In [112]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [114]:
3 / y

array([[0.6       , 0.5       ],
       [0.42857143, 0.375     ]])

# Elementwise Functions

In [115]:
# Estas funciones se aplican a todos los elementos de la matriz... 
# hay muchas, coseno, seno, sqrt, exp... etc

In [117]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [118]:
y = np.sin(np.pi * x)
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [119]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [120]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Aggregate Functions

In [2]:
who

np	 


In [7]:
data = np.random.normal(size=(15,15))

In [5]:
data.size

225

In [8]:
# Para hallar la media 2 opciones, como en muchas ocasiones.. un método o una función np
np.mean(data)
# igual que data.mean()

0.031756243643754546

Tenemos opciones para hallar:
* media, desviación estándar, varianza, suma, producto, 
* suma acumulativa, producto acumulativo, minimo, máximo
* índice con valor mínimo, índice de valor máximo, 
* np.all y np.any que retornan True o False según ...

In [10]:
data = np.random.normal(size=(5, 10, 15))
data.sum(axis=0).shape 
# Indica que la agregación se lleva a cabo en el primer eje, con lo que el resultante es
# una matriz de 10 x 15  (cada uno de esos 150 ítems lleva la suma a lo largo del eje x)

(10, 15)

In [11]:
data.sum(axis=(0, 2)).shape  # aquí queremos suma en los ejes x , z.---- por tanto cada elemento y va a tener la suma de tods
# los elementos... o sea el resultado será un vector, con vi = suma data[x,i,z] para todos los x del primer eje, z del tercer

(10,)

In [15]:
data.sum(axis=(0, 2))

array([  4.17860305,  -4.83902929,  -4.51636489,  -3.81875536,
        -0.43929712,  -2.89075087,   1.20091363, -17.74322542,
         6.98931954,   4.3620002 ])

In [16]:
data.sum() # pues suma todo  (o sea, en todos los ejes<9) y nos da un solo valor, la suma

-17.516586528380095

# Boolean Arrays and Conditional Expressions

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
a < b

array([ True,  True, False, False])

In [18]:
a[a < b]

array([1, 2])

In [24]:
3 * a + 2 > a * b + 4

array([False, False,  True,  True])

In [25]:
a[3 * a + 2 > a * b + 4]

array([3, 4])

In [26]:
np.all(a < b)

False

In [27]:
np.any(a < b)

True

In [28]:
x = np.array([-2, -1, 0, 1, 2])
x > 0

array([False, False, False,  True,  True])

In [29]:
2 * (x > 0)

array([0, 0, 0, 2, 2])

In [30]:
x * (x > 0)  # es una forma de conseguir un vector donde solo están las componenetes positivas

array([0, 0, 0, 1, 2])

In [33]:
A = np.array([[-1, 2, -5], [2, -1, 4], [1, -2, 0]])
A

array([[-1,  2, -5],
       [ 2, -1,  4],
       [ 1, -2,  0]])

In [34]:
A * (A > 0)

array([[0, 2, 0],
       [2, 0, 4],
       [1, 0, 0]])

The np.where function selects elements from two arrays (second and third arguments), given a Boolean-valued
array condition (the first argument). For elements where the condition is True, the corresponding values from the array given as second argument are selected, and if the condition is False, elements from the third argument array are selected:

In [37]:
x = np.linspace(-4, 4, 9)
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [36]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

Muchísimas funciones interesantes:
* np.where: Chooses values from two arrays depending on the value of a condition array.
* np.choose: Chooses values from a list of arrays depending on the values of a given index array.
* np.select: Chooses values from a list of arrays depending on a list of conditions.
* nonzero: returns an array with indices of nonzero elements
* np.logical_and Performs an elementwise ANd operation.
* np.logical_or, np.logical_xor elementwise or/Xor operations.
* np.logical_not elementwise NoT operation (inverting).


# Set Operations

In [39]:
a = np.unique([1, 2, 3, 3])
a

array([1, 2, 3])

In [40]:
b = np.unique([2, 3, 4, 4, 5, 6, 5])
b

array([2, 3, 4, 5, 6])

In [41]:
np.in1d(a, b)  # testea si cada uno de los valores del primer array existe en el segundo array... (no tienen por qué ser únicos)

array([False,  True,  True])

In [43]:
np.intersect1d(a, b)  # elements that are contained in two given arrays.

array([2, 3])

In [45]:
np.setdiff1d(a, b) # returns an array with elements that are contained in one
# but not the other, of two given arrays.

array([1])

In [46]:
np.union1d(a, b)  # pues la unión


array([1, 2, 3, 4, 5, 6])

In [47]:
# También podemos usar "in" para testear si un valor está en un array
1 in a

True

In [48]:
1 in b

False

In [49]:
# Como testear si a es subconjunto de b??? Pues sencillo, si todos los elementos de a están en b...
# O sea, np.in1d(a, b) debe ser todo True... que lo verificamos con all
np.all(np.in1d(a, b))

False

In [50]:
data = np.random.randn(1, 2, 3, 4, 5)
data.shape

(1, 2, 3, 4, 5)

In [52]:
# Podemoshacer la transpuesta con data.T o data.transpose
data.T.shape

(5, 4, 3, 2, 1)

In [53]:
# Método np.fliplr y np.flipud nos devuelven la matriz flipeada (creo que es un view, que no se crea nada nuevo)

In [54]:
# similarmente np.rot90 rota...

# Matrix and Vector Operations


Muchísimas funciones interesantes:
* np.dot Matrix multiplication (dot product) between two given arrays representing vectors, arrays, or tensors.
* np.inner scalar multiplication (inner product) between two arrays representing vectors.
* np.cross The cross product between two arrays that represent vectors.
* np.tensordot dot product along specified axes of multidimensional arrays.
* np.outer outer product (tensor product of vectors) between two arrays representing vectors.
* np.kron Kronecker product (tensor product of matrices) between arrays representing matrices and higher-dimensional arrays.
* np.einsum evaluates einstein’s summation convention for multidimensional arrays.

In [55]:
# Recordar que * es para elementwise multiplication
# Para multiplicar matrices podemos usar el operador @ o simplemente la función np.dot

In [56]:
# Se puede liar bastante la cosa, simplemente para evaluar el producto  A' = B A B-1 de tres matrices...
A = np.random.rand(3,3)
B = np.random.rand(3,3)
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))   ## uf es muy largo
# también valdría Ap = B.dot(A.dot(np.linalg.inv(B)))

In [57]:
# Para solucionar esto podemos tranformar una array de matriz A en un nuevo objeto matriz
# que si interpreta el oeprador * como matriz... y además tiene una propiedad para la inversa
A = np.matrix(A)
B = np.matrix(B)
Ap = B * A * B.I


```This may seem like a practical compromise, but unfortunately using the matrix class
does have a few disadvantages, and its use is therefore often discouraged. The main
objection against using matrix is that expression like A * B is then context dependent:
that is, it is not immediately clear if A * B denotes elementwise or matrix multiplication,
because it depends on the type of A and B, and this creates another code-readability
problem.```