In [1]:
import numpy as np

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
ndarray??

Object `ndarray` not found.


In [5]:
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [6]:
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [7]:
data.Size

AttributeError: 'numpy.ndarray' object has no attribute 'Size'

In [8]:
data.size

6

In [9]:
data.nbytes

24

In [10]:
data.dtype

dtype('int32')

In [11]:
data.shape

(3, 2)

In [12]:
data.ndim

2

In [13]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
type(data)

numpy.ndarray

In [1]:
x = np.array([1, 2, 3])

NameError: name 'np' is not defined

In [2]:
who


Interactive namespace is empty.


In [3]:
import numpy as np

In [4]:
who

np	 


In [5]:
x = np.array([1, 2, 3])

In [6]:
x

array([1, 2, 3])

In [7]:
x.shape


(3,)

In [8]:
x.reshape?

Docstring:
a.reshape(shape, order='C')

Returns an array containing the same data with a new shape.

Refer to `numpy.reshape` for full documentation.

See Also
--------
numpy.reshape : equivalent function

Notes
-----
Unlike the free function `numpy.reshape`, this method on `ndarray` allows
the elements of the shape parameter to be passed in as separate arguments.
For example, ``a.reshape(10, 11)`` is equivalent to
``a.reshape((10, 11))``.
Type:      builtin_function_or_method


In [9]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [10]:
y = x.reshape((3, 1))

In [11]:
x

array([1, 2, 3])

In [12]:
y

array([[1],
       [2],
       [3]])

In [13]:
x.shape

(3,)

In [14]:
y.shape

(3, 1)

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [16]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
A.shape

(4, 3)

In [18]:
a = np.array([[1, 2, 3]])

In [19]:
a

array([[1, 2, 3]])

In [20]:
a.shape

(1, 3)

In [21]:
a = np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`. See the warnings section below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
  

In [ ]:
a = np.arange

In [25]:
a = np.arange(0, 6, 0.5).reshape(4, 3)

In [26]:
a

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [27]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
A[2, 1]

8

In [30]:
A[2]

array([7, 8, 9])

In [32]:
A[2,]

array([7, 8, 9])

In [34]:
A.transpose

<function ndarray.transpose>

In [35]:
A.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [36]:
A = np.arange(9).reshape(3, 3)

In [37]:
A


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
A.diagonal

<function ndarray.diagonal>

In [39]:
A.diagonal?

Docstring:
a.diagonal(offset=0, axis1=0, axis2=1)

Return specified diagonals. In NumPy 1.9 the returned array is a
read-only view instead of a copy as in previous NumPy versions.  In
a future version the read-only restriction will be removed.

Refer to :func:`numpy.diagonal` for full documentation.

See Also
--------
numpy.diagonal : equivalent function
Type:      builtin_function_or_method


In [40]:
a.diagonal()

array([0., 2., 4.])

In [41]:
a

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [42]:
a.diagonal(offset=1)

array([0.5, 2.5])

In [43]:
t = np.arange(36).reshape(3, 3, 4)

In [44]:
t

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [45]:
t.shape

(3, 3, 4)

In [46]:
t[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
t[0, 1]

array([4, 5, 6, 7])

In [48]:
t[0][1]

array([4, 5, 6, 7])

In [50]:
t[1, 1, 3] == t[1, 1, 3]

True

In [51]:
np.newaxis

In [52]:
np.newaxis??

Type:        NoneType
String form: None
Docstring:   <no docstring>


In [53]:
np.newaxis?

Type:        NoneType
String form: None
Docstring:   <no docstring>


In [55]:
t = np.array([[1, 2, 3], [4, 5, 6]])

In [62]:
u = t[np.newaxis,1, :]

In [63]:
u

array([[4, 5, 6]])

In [64]:
t = np.arange(15).reshape(5, 3)

In [65]:
t

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [68]:
u = t[1:4, 0:2]

*Con esto conseguimos crear un nuevo array utilizando de las filas 1 a 4 (sin incluir), y con las columnas 0 a 2 (sin incluir)*

In [67]:
u

array([[ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [70]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([10, 100, 1000])
d = np.array([10, 11])

*Suma componente a componente*

In [73]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

*Lo mismo para resta, mult., división, potencia... lo hace, si tienen igual forma, componente a componente*

In [75]:
a * b
# Esto no es matricial, es componente a componente!!

array([[ 7, 16, 27],
       [40, 55, 72]])

In [76]:
# Si las dimensiones son distintas se aplica el Broadcasting...
2 * a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [77]:
# Broadcasting al hacer a + c
# a matriz 2x3 y c vector longitud 3, pues se suma a cada fila el vector c...
a + c

array([[  11,  102, 1003],
       [  14,  105, 1006]])

In [78]:
# Lo mismo claro si hiciéramos a * c, a - c, a ** c, etc

In [80]:
# Podremos hacer broadcast del vector d (2 componentes) con la matriz a???
a + d

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [83]:
# No se puede, porque las filas tienen distinto tamaño...
# podríamos arreglarlo transformando d en un vector columna de tamaño 2,
# y entonces ya sí, pq la matriz a también tiene dos filas...
d = d.reshape(2, 1)  
a + d  # ahora se hace broadcast del vector d, a las distintas columnas 

array([[11, 12, 13],
       [15, 16, 17]])

# Módulo (magnitude en inglés)...

In [84]:
u = np.array([2, -4, 3])

In [96]:
# Módulo
modulo_u = np.sqrt(sum(u * u))  # también podría ser, claro, con math.sqrt....
# también, si queremos podemos utilziar la función suma de numpy
modulo_v2 = np.sqrt((u * u).sum())


In [97]:
# Vector unitario...
unit_u = u / modulo_u

In [98]:
unit_u

array([ 0.37139068, -0.74278135,  0.55708601])

In [99]:
# O sea, parece que no hay funciones para el cálculo del módulo ni del vector unitario!!!

In [114]:
# Transponer... con el reshape o más fácil con método transpose() o on .T
# Cuidado, esto no afecta si son vectores... en este caso, si fueran vectores, tendríamos
# que hacer el reshape
v= np.array([1, 2, 3])
v_t = v.T  # NO HACE NADA, pq es un vctor
v_t = v.transpose()  # NO HACE NADA
# Cuando es un vector, hay que hacer manualmente el transpose utilziando el resphape
v_t = v.reshape(3, 1)

In [103]:
v_t

array([[1],
       [2],
       [3]])

In [109]:
# Cuidado si ahora volvemos a hacer el transpose, o el reshape, no nos quedará el mismo vector
v_t_t = v_t.T  # array([[1, 2, 3]])
v_t_t = v_t.reshape(1, 3) # array([[1, 2, 3]])

In [115]:
# A no ser que lo dejamos con una dimensión solo, claro entonces sí
v_t_t = v_t.reshape(3)
# Así sería un vector, antes era una matriz



In [116]:
v_t_t

array([1, 2, 3])

# Producto escalar de vectores (dot product o producto interior)

In [118]:
# Propiedad geométrica.... a . b = |a| . |b| . cos(alpha)
# Obviamente a . a = |a| ^ 2

In [119]:
# Como básicamente es multiplicar componente a componente y sumar todo simplemnte la formula sería...
# a . b = (a * b).sum() 

In [120]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
producto_escalar = (a*b).sum()

In [121]:
producto_escalar

70

In [122]:
# YA EXISTE FUNCIÓN EN NUMPY
producto_escalar = np.dot(a, b)

In [123]:
producto_escalar

70

In [125]:
# Para calcular el coseno del ángulo que forman , simplemente
# cos alpha = a . b / (|A| * |B|)
coseno = np.dot(a, b) / np.sqrt(np.dot(a, a) * np.dot(b, b))

In [126]:
coseno

0.9688639316269664

In [127]:
angulo = np.arccos(coseno)

In [128]:
angulo

0.2501959204225109

In [130]:
# Lo pasamos de radianes a grados
angulo_grados = angulo * 180 / np.pi

In [131]:
angulo_grados

14.335170291600873

# Proyección de a sobre b... (proj_b a)
$$
proj_{b}a = \frac{a \cdot b}{|b|^2} \cdot\vec{b}
$$

## Producto exterior de vectores... (pueden tener distinto tamaño)
np nos proporciona el método np.outer
Consiste básicamente en obtener una matriz, donde el elemnto ij es el producto del elemento i de a por el elemento j de b


# Producto vectorial (cross product) de vectores
**Sólo definido en 3D**  
ES UN VECTOR (de ahí el nombre en español)  
a x b = |a| |b| sin(alpha) vector normal
$$
\vec{a} x \vec{b} = |a| |b| \sin(\theta) \cdot \vec{n}
$$

In [133]:
# es el método np.cross

# Observación... en términos matriciales....
y entendiendo que los vectores son vectores columna... originalmente
Producto escalar a . b es simplemente el producto de las matrices aT b   (matriz fila 1xn por matriz columna nx1) --> genera matriz 1x1 = escalar
Producto exterior a b es simplmenete a bT (matriz de nx1 por matriz de 1xm --> genera matriz nxm)

# Multiplicación de matrices... 2 posibilidades... funcionan bien ambas
np.dot --> es lo mismo que hemos visto para realizar el prodcuto interior...  
np.matmul.  
**También podemos utilizar el operador @**  
Observar que hay diferencias entre np.dot y np.matmul... pero no las hay para 1 y 2 dimensiones

# También está el producto de Kronecker de dos matrices...
Básicamente es una supermatriz, gigantesca, construida por bloques...   
para el primer bloque multiplicamos a00 por toda la matriz B, etc

In [139]:
# Una matriz M de mxn representa tb una transformación lineal entre puntos de Rm a puntos de Rn de esta forma...
# x de Rm --> y = M . x de Rn
# Ejemplo M matriz que representa transformación lineal de R4 a R2
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
x = np.array([11, 12, 13, 14])
y = np.dot(M, x)

In [138]:
y

array([130, 330])

In [140]:
# En el caso de matrices cuadradas, por ejemplo de 3x3, representan una transformación lineal de R3 en R3
# Lo mismo para R2
# Estas trans. son lineales, llevan el 0 al 0, propiedades lineales, etc
# En particular las hay de tipo rotación...

In [143]:
# Rotación en R2 con una matriz de giro... giro de 45 º
alpha = np.pi / 4
R = np.array([[np.cos(alpha), - np.sin(alpha)], [np.sin(alpha), np.cos(alpha)]])

In [144]:
R

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [145]:
# Lo mismo hay para R3... según el eje es distinta...
Rx = np.array([[1, 0, 0], [0, np.cos(alpha), - np.sin(alpha)], [0, np.sin(alpha), np.cos(alpha)]])
Ry = np.array([[np.cos(alpha),0, np.sin(alpha)], [0, 1, 0], [- np.sin(alpha), 0, np.cos(alpha)]])
Rz = np.array([[np.cos(alpha), - np.sin(alpha), 0], [np.sin(alpha), np.cos(alpha), 0], [0, 0, 1]])


In [152]:
# Si quisiéramos representar una transformación afín y = Ax + b también podríamos hacerlo de 
# forma parecida, simplemente añadiendo una columna y fila más a la matriz...
# Ejemplo para R2: y = Ax + b con A = ((2, 1), (3, -4)) y b la traslación (5, 7)
A = np.array([[2, 1], [3, -4]])
b = np.array([2, 7])
x = np.array([7, 9])
nueva_A = np.array([[2, 1, 5], [3, -4, 7], [0, 0, 1]])
nuevo_x = np.array([7, 9, 1])
nuevo_y = np.dot(nueva_A, nuevo_x)


In [153]:
nuevo_y

array([28, -8,  1])

In [154]:
# Luego el y correspondiente es (28, -8)

In [158]:
# La diagonal normalmente es sólo para matrices cuadradas, pero numpy tb la calcula para cualquiera
# lo Mismo con la traza, que es la suma de la diagonal...
b = np.array([[1,2,3,4],[5,6,7,8], [2, -3, -4, 0]])

In [159]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 2, -3, -4,  0]])

In [160]:
np.diag(b)

array([ 1,  6, -4])

In [161]:
np.trace(b)

3

In [162]:
# Potencia de una Matriz... aunque se puede ir multiplicando por sí misma, lo
# mejor es utilziar el método matrix_power (hay que importarlo desde numpy.linalg)
A = np.array([[1, 2], [3, 4]])

In [164]:
np.dot(A, A)

array([[ 7, 10],
       [15, 22]])

In [165]:
from numpy.linalg import matrix_power
matrix_power(A, 2)

array([[ 7, 10],
       [15, 22]])

In [168]:
# Elevar al cubo es lioso multiplicando...
np.dot(A, np.dot(A, A))

array([[ 37,  54],
       [ 81, 118]])

In [169]:
# Aunque se puede usar el operador @ para el producto de matrices...
# Veamos para elevar a la 4....
A @ A @ A @ A

array([[199, 290],
       [435, 634]])

In [170]:
# Es más sencillo y optimizado utilziar matrix_power...
matrix_power(A, 4)

array([[199, 290],
       [435, 634]])

In [171]:
matrix_power(A, 10)

array([[ 4783807,  6972050],
       [10458075, 15241882]])

In [172]:
# Esto sería muy incómodo....
A @ A @ A @ A @ A @ A @ A @ A @ A @ A

array([[ 4783807,  6972050],
       [10458075, 15241882]])

# Generación de matrices especiales
Podemos generar rápidamente matrices llenas de 0, 1, números aleatorios, etc

In [173]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [176]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [177]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [178]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [182]:
# np.eye es exactamente lo mismo que np.identity es un alias...
np.eye(7, dtype=np.int8)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int8)

# Matrices triangulares
np.triu (upper) nos devuelve la matriz triangular superior asociada a otra matriz (descartando los valores q están debajo)  
np.tril  (lower) nos devuleve la matr. triang. inferior...

In [187]:
A = np.arange(1, 17, 1).reshape(4, 4)

In [188]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [189]:
np.triu(A)

array([[ 1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0,  0, 11, 12],
       [ 0,  0,  0, 16]])

In [190]:
np.tril(A)

array([[ 1,  0,  0,  0],
       [ 5,  6,  0,  0],
       [ 9, 10, 11,  0],
       [13, 14, 15, 16]])

# Determinantes...
np.linalg.det

In [196]:
a = np.array([[1, 2], [3, 4]], dtype=int)

In [201]:
np.linalg.det(a)

-2.0000000000000004

In [200]:
np.linalg.det(np.triu(A))

1056.0

# Matriz inversa

In [205]:
# usaremos np.linalg.inv
# Sólo posible si es una matriz cuadrada cuyo determinante no es 0
# Si fuera 0 no tiene inversa y se llama matriz singular

In [203]:
a = np.array([[1,2,1],[2,1,2],[1,2,2]])

In [204]:
a

array([[1, 2, 1],
       [2, 1, 2],
       [1, 2, 2]])

In [207]:
b = np.linalg.inv(a)

In [208]:
b

array([[ 0.66666667,  0.66666667, -1.        ],
       [ 0.66666667, -0.33333333,  0.        ],
       [-1.        ,  0.        ,  1.        ]])

In [209]:
# Comprobemos que el producto es la matriz identidad
a @ b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Vectores y valores propios (eigenvectors y eigenvalues)

Dada una matriz cuadrada hallar los vectores propios consiste en hallar los vectores para los que la transformación lineal y = Av nos da un vector con la misma dirección...
O sea,
$$
A \cdot \vec{v} = \lambda \vec{v}
$$

O sea, el problema consiste en hallar los vectores (las direcciones) y sus multiplicadores (valores)

In [210]:
# Observar que para la matriz identidad, cualquier vector es un vector propio...