In [1]:
import tensorflow as tf

In [5]:
x = tf.Variable(0.)


In [6]:
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)

In [7]:
grad_of_y_wrt_x

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [10]:
x = tf.Variable(tf.random.uniform((2, 2)))
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.02341592, 0.42188716],
       [0.42652524, 0.08335185]], dtype=float32)>

In [11]:
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)

In [12]:
grad_of_y_wrt_x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [13]:
W = tf.Variable(tf.random.uniform((2, 2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2, 2))

In [14]:
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b

In [15]:
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])