In [1]:
import tensorflow as tf

In [3]:
x = tf.ones(shape=(2, 1))

In [4]:
x  # Es un objeto de la clase Tensor

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [7]:
# También podemos crear un Tensor utilizando tf.zeros
x = tf.zeros(shape=[2, 1])  # para indicar la forma simplemente dar una secuencia, da igual tupla, que lista...

In [6]:
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

# también podemos crear tensores utilizando distribuciones de probabilidad...
* Normal
* Uniforme


In [8]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)

In [11]:
y = tf.random.uniform(shape=(1, 3), minval=0., maxval=1.)

In [12]:
y

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.1783613, 0.779842 , 0.8865706]], dtype=float32)>

In [14]:
# Cuidado, los tensores, a diferencia de los arrays de numpy, NO SON ASIGNABLES
import numpy as np
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
x[1, 1] = 14.3
x

array([[ 1. ,  1. ,  1. ],
       [ 1. , 14.3,  1. ]])

In [ ]:
x = tf.ones(shape=(2, 2))
x[1, 1] = 14.3  # Error.... los tensores no soportan asignación!!!!

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [21]:
# Cómo hacemos entonces para cambiar los tensores de una red neuronal???
# Utilizaremos tf.Variable.... 
v = tf.Variable(initial_value=tf.ones(shape=(2, 2)))
v  # Es de tipo tf.Variable !

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [24]:
# Para cambiar el valor utilizar método... no vale con índices
v.assign(tf.random.normal(shape=(2, 2)))  # Cuidado, debe ser de la misma shape...

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[-0.97796005, -1.7390875 ],
       [ 0.07311287,  0.66391504]], dtype=float32)>

In [27]:
# También podemos cambiar algún rango de subíndices..
v[0].assign([1.2, 1.3])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[1.2       , 1.3       ],
       [0.07311287, 0.66391504]], dtype=float32)>

In [28]:
v[1, 1].assign(13.2)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[ 1.2       ,  1.3       ],
       [ 0.07311287, 13.2       ]], dtype=float32)>

In [29]:
# Y podemos sumarle y restarle cosas y otro tipo de operaciones...
v.assign_add(tf.ones((2, 2)))  # esto es como hacer +=

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[ 2.2      ,  2.3      ],
       [ 1.0731128, 14.2      ]], dtype=float32)>

In [30]:
v.assign_sub(tf.ones((2, 2)))  # Esto es como -=

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[ 1.2       ,  1.3       ],
       [ 0.07311285, 13.2       ]], dtype=float32)>

# Operaciones con tensores

In [32]:
a = 2 * tf.ones((2, 2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [35]:
b = 3 + tf.square(a)
b  # eleva cada uno de los elementos de la matriz a, y luego le suma 3 a cada uno de ellos

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7., 7.],
       [7., 7.]], dtype=float32)>

In [36]:
c = tf.sqrt(b)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6457512, 2.6457512],
       [2.6457512, 2.6457512]], dtype=float32)>

In [38]:
d = b + c
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[9.645751, 9.645751],
       [9.645751, 9.645751]], dtype=float32)>

In [40]:
e = tf.matmul(a, b)
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[28., 28.],
       [28., 28.]], dtype=float32)>

In [42]:
e *= d
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[270.08102, 270.08102],
       [270.08102, 270.08102]], dtype=float32)>

### GradientTape API

In [44]:
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
gradient
# La derivada de result = x ^2 respecto a x sería 2x, que si x vale 3 se evalúa a 6

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [48]:
input_var.assign(5)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
gradient  # Como la derivada es 2x, si la variable x vale 5, el valor será 10

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [51]:
# Ahora si y = 2x ^3 - 3x ^2 + 6x - 8
# La derivada es y' = 6x ^2 - 6 x
# La derivada en -2 sería  y'(-2) = 6 x^2 - 6x + 6 = 24 + 12 + 6 = 42
x = tf.Variable(initial_value=-2.0)
with tf.GradientTape() as tape:
    y = 2 * tf.square(x) * x - 3 * tf.square(x) + 6 * x - 8
gradient = tape.gradient(y, x)
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [54]:
# Ahora una superficie...
x = tf.Variable(initial_value=-2.0)
y = tf.Variable(initial_value=6.0)
with tf.GradientTape() as tape:
    z = 2 * tf.square(x) * y - 3 * x * tf.square(y) + 6 * x * y - 8 * y + 14
gradient = tape.gradient(z, (x, y))
gradient

(<tf.Tensor: shape=(), dtype=float32, numpy=-120.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=60.0>)

In [55]:
# El gradiente sale...
# Derivada parcial de z respecto a x: 4xy - 3y2 + 6y = -48 - 108 + 36  = -120
# Derivada parcial de z respecto a y: 2x2 - 6xy + 6x - 8 = 8 + 72 - 12 - 8 = 60 

In [59]:
# GradientTape sirve tb. para otro tipo de tensores, aunque no sean variables
# Pero por defecto sólo vigila las variables trainables (los pesos)..
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)

In [61]:
print(gradient)

None


In [64]:
# Esto ocurre pq hay que decirle que tenga en cuenta el tensor input_const....!!!
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)  # Hace falta decirle esto!!!
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)

In [63]:
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [71]:
# También se pueden calcular las derivadas parciales de segundo orden, segundas derivadas, etc...
time = tf.Variable(2.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time ** 2
    speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)

In [69]:
acceleration

<tf.Tensor: shape=(), dtype=float32, numpy=9.8>

In [72]:
speed

<tf.Tensor: shape=(), dtype=float32, numpy=19.6>